services:
  - type: web
    name: powerlifting-backend
    env: python
    plan: free
    repo: .
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    disk: 1024
    envVars:
      - key: ADMIN_KEY
        sync: false
  - type: static
    name: powerlifting-frontend
    plan: free
    repo: .
    staticPublishPath: frontend
    buildCommand: ""